version: '3'
services:
  client:
    build:
      context: ./client
    volumes:
      - ./client:/src
    ports:
      - 3000:3000
    command: sh -c "cd app && npm install && npm start"
    tty: true

  api:
    build:
      context: ./api
    image: "fastapi"
    volumes:
      - ./api:/src
    ports:
      - "9004:9004"
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 9004